---

name: RELEASE

'on':
  push:
    branches:
      - main

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.PAT_CLASSIC }}
  SEMANTIC_RELEASE_PACKAGES: '@semantic-release/github'

jobs:
  release:
    permissions:
      contents: write
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install ${{ env.SEMANTIC_RELEASE_PACKAGES }} -D

      - name: Release
        run: npx semantic-release
